export enum Severity {
    LIE = "LIE",
    OBJECTOVE_FALSEHOOD = "OBJECTOVE_FALSEHOOD",
    MISLEADING = "MISLEADING",
    HYPOCRISY = "HYPOCRISY",
    SUBJECTIVE_FALSEHOOD = "SUBJECTIVE_FALSEHOOD",
    FAULTY_LOGIC = "FAULTY_LOGIC"
}